# Data Preprocessing Tools

## Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [68]:
dataset=pd.read_csv('/content/datasets_596958_1073629_Placement_Data_Full_Class.csv')
dataset.shape
dataset.head()

sl_no gender  ssc_p    ssc_b  ...  specialisation  mba_p      status    salary
0      1      M  67.00   Others  ...          Mkt&HR  58.80      Placed  270000.0
1      2      M  79.33  Central  ...         Mkt&Fin  66.28      Placed  200000.0
2      3      M  65.00  Central  ...         Mkt&Fin  57.80      Placed  250000.0
3      4      M  56.00  Central  ...          Mkt&HR  59.43  Not Placed       NaN
4      5      M  85.80  Central  ...         Mkt&Fin  55.50      Placed  425000.0

[5 rows x 15 columns]

In [0]:
X=dataset.iloc[:,7].values.reshape(-1,1)
Y=dataset.iloc[:,12].values.reshape(-1,1)

In [70]:
print(X)

[[58.  ]
 [77.48]
 [64.  ]
 [52.  ]
 [73.3 ]
 [67.25]
 [79.  ]
 [66.  ]
 [72.  ]
 [61.  ]
 [60.  ]
 [78.3 ]
 [65.  ]
 [59.  ]
 [50.  ]
 [69.  ]
 [65.6 ]
 [64.  ]
 [64.  ]
 [70.  ]
 [66.  ]
 [85.  ]
 [72.23]
 [64.74]
 [78.86]
 [50.2 ]
 [66.  ]
 [66.  ]
 [67.5 ]
 [58.  ]
 [73.  ]
 [65.  ]
 [66.4 ]
 [81.  ]
 [52.  ]
 [72.  ]
 [57.  ]
 [65.6 ]
 [66.  ]
 [64.  ]
 [80.  ]
 [65.  ]
 [65.  ]
 [68.  ]
 [81.  ]
 [72.  ]
 [65.6 ]
 [57.  ]
 [68.  ]
 [52.  ]
 [68.4 ]
 [56.2 ]
 [53.  ]
 [72.  ]
 [69.  ]
 [65.  ]
 [61.4 ]
 [74.  ]
 [68.  ]
 [72.11]
 [72.  ]
 [66.89]
 [67.4 ]
 [64.  ]
 [75.  ]
 [57.  ]
 [66.  ]
 [67.  ]
 [72.7 ]
 [66.  ]
 [62.  ]
 [71.  ]
 [78.  ]
 [71.72]
 [70.2 ]
 [77.5 ]
 [71.93]
 [65.  ]
 [64.5 ]
 [66.  ]
 [69.  ]
 [67.  ]
 [74.  ]
 [68.  ]
 [70.  ]
 [77.2 ]
 [64.  ]
 [60.  ]
 [73.  ]
 [69.  ]
 [82.  ]
 [50.8 ]
 [66.  ]
 [54.  ]
 [64.  ]
 [65.  ]
 [76.  ]
 [61.  ]
 [65.  ]
 [63.  ]
 [58.  ]
 [68.  ]
 [68.  ]
 [73.  ]
 [65.  ]
 [58.  ]
 [54.  ]
 [83.  ]
 [69.  ]
 [65.  ]
 [72.  ]
 

In [71]:
print(Y)

[[58.8 ]
 [66.28]
 [57.8 ]
 [59.43]
 [55.5 ]
 [51.58]
 [53.29]
 [62.14]
 [61.29]
 [52.21]
 [60.85]
 [63.7 ]
 [65.04]
 [68.63]
 [54.96]
 [64.66]
 [62.54]
 [67.28]
 [64.08]
 [77.89]
 [56.7 ]
 [69.06]
 [68.81]
 [63.62]
 [74.01]
 [65.33]
 [57.55]
 [57.69]
 [64.15]
 [51.29]
 [56.7 ]
 [58.32]
 [62.21]
 [72.78]
 [62.77]
 [62.74]
 [51.45]
 [55.47]
 [56.86]
 [62.56]
 [66.72]
 [69.76]
 [51.21]
 [62.9 ]
 [69.7 ]
 [66.53]
 [71.63]
 [54.55]
 [62.46]
 [56.11]
 [62.98]
 [62.65]
 [65.49]
 [71.04]
 [65.56]
 [52.71]
 [66.88]
 [63.59]
 [57.99]
 [56.66]
 [57.24]
 [62.48]
 [59.69]
 [59.5 ]
 [58.78]
 [57.1 ]
 [58.46]
 [60.99]
 [59.24]
 [68.07]
 [65.45]
 [66.94]
 [68.53]
 [59.75]
 [67.2 ]
 [67.  ]
 [64.27]
 [57.65]
 [59.42]
 [67.99]
 [62.35]
 [70.2 ]
 [60.44]
 [66.69]
 [62.  ]
 [76.18]
 [57.03]
 [59.08]
 [64.36]
 [62.36]
 [68.03]
 [62.79]
 [59.47]
 [55.41]
 [54.97]
 [62.16]
 [64.44]
 [69.03]
 [57.31]
 [59.47]
 [64.95]
 [60.44]
 [61.31]
 [65.83]
 [58.23]
 [55.3 ]
 [65.69]
 [73.52]
 [58.31]
 [56.09]
 [54.8 ]
 

## Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1)

In [73]:
print(X_train)

[[57.  ]
 [66.  ]
 [66.  ]
 [68.  ]
 [80.  ]
 [70.67]
 [53.  ]
 [60.  ]
 [64.5 ]
 [63.  ]
 [73.  ]
 [60.  ]
 [82.  ]
 [65.  ]
 [67.  ]
 [78.  ]
 [65.  ]
 [69.  ]
 [69.  ]
 [66.6 ]
 [73.  ]
 [50.  ]
 [67.  ]
 [64.27]
 [61.4 ]
 [59.79]
 [65.  ]
 [73.  ]
 [72.  ]
 [72.  ]
 [58.  ]
 [71.25]
 [65.  ]
 [65.  ]
 [64.  ]
 [67.25]
 [56.3 ]
 [69.2 ]
 [68.  ]
 [56.  ]
 [66.  ]
 [91.  ]
 [69.  ]
 [69.  ]
 [68.  ]
 [64.33]
 [58.  ]
 [65.  ]
 [64.2 ]
 [65.  ]
 [65.  ]
 [79.  ]
 [64.  ]
 [56.  ]
 [65.  ]
 [60.  ]
 [65.  ]
 [67.  ]
 [77.5 ]
 [58.  ]
 [59.  ]
 [61.  ]
 [74.  ]
 [60.  ]
 [72.  ]
 [72.  ]
 [64.6 ]
 [73.  ]
 [57.  ]
 [55.  ]
 [57.  ]
 [74.  ]
 [73.  ]
 [59.  ]
 [73.  ]
 [72.  ]
 [61.  ]
 [77.5 ]
 [85.  ]
 [50.8 ]
 [63.35]
 [64.  ]
 [62.  ]
 [77.2 ]
 [77.25]
 [79.  ]
 [62.8 ]
 [67.  ]
 [65.  ]
 [67.  ]
 [57.  ]
 [65.6 ]
 [70.2 ]
 [66.  ]
 [59.9 ]
 [60.  ]
 [65.  ]
 [60.  ]
 [66.4 ]
 [64.  ]
 [68.  ]
 [58.  ]
 [58.  ]
 [73.  ]
 [64.74]
 [75.5 ]
 [61.  ]
 [69.  ]
 [65.  ]
 [64.  ]
 [69.  ]
 

In [74]:
print(Y_train)

[[54.55]
 [60.11]
 [57.69]
 [57.99]
 [66.72]
 [60.39]
 [60.22]
 [53.2 ]
 [59.42]
 [59.47]
 [64.36]
 [69.28]
 [68.03]
 [62.92]
 [60.99]
 [71.43]
 [56.81]
 [55.01]
 [58.4 ]
 [70.85]
 [67.05]
 [54.96]
 [64.86]
 [66.23]
 [66.88]
 [57.29]
 [52.71]
 [71.77]
 [71.04]
 [54.8 ]
 [61.3 ]
 [63.23]
 [62.16]
 [51.21]
 [67.28]
 [51.58]
 [64.74]
 [66.94]
 [62.46]
 [52.64]
 [58.46]
 [69.71]
 [62.36]
 [65.56]
 [61.31]
 [61.26]
 [55.3 ]
 [57.31]
 [72.14]
 [56.49]
 [65.04]
 [70.81]
 [53.49]
 [56.63]
 [62.48]
 [52.38]
 [72.29]
 [70.2 ]
 [54.48]
 [60.23]
 [68.63]
 [62.5 ]
 [60.44]
 [53.39]
 [61.01]
 [66.53]
 [64.34]
 [65.83]
 [51.45]
 [59.32]
 [55.8 ]
 [74.56]
 [56.7 ]
 [58.81]
 [69.72]
 [66.04]
 [62.93]
 [67.  ]
 [69.06]
 [62.79]
 [65.52]
 [57.8 ]
 [65.45]
 [76.18]
 [66.06]
 [53.29]
 [56.6 ]
 [75.71]
 [57.65]
 [63.08]
 [57.1 ]
 [71.63]
 [67.2 ]
 [59.47]
 [65.99]
 [59.08]
 [62.28]
 [60.85]
 [62.21]
 [61.58]
 [66.69]
 [58.79]
 [64.95]
 [73.33]
 [63.62]
 [68.2 ]
 [52.21]
 [61.82]
 [58.23]
 [66.46]
 [65.63]
 

In [75]:
print(X_test)

[[69.  ]
 [61.  ]
 [54.  ]
 [83.  ]
 [56.2 ]
 [81.  ]
 [72.11]
 [84.  ]
 [73.3 ]
 [65.  ]
 [78.  ]
 [64.  ]
 [54.  ]
 [66.  ]
 [57.5 ]
 [61.  ]
 [64.  ]
 [61.  ]
 [75.  ]
 [66.  ]
 [81.  ]
 [65.  ]
 [70.  ]
 [64.  ]
 [64.  ]
 [72.  ]
 [71.72]
 [69.3 ]
 [70.  ]
 [67.4 ]
 [61.26]
 [64.21]
 [52.  ]
 [78.3 ]
 [58.  ]
 [58.  ]
 [58.  ]
 [56.  ]
 [60.  ]
 [67.5 ]
 [65.6 ]
 [65.  ]
 [72.  ]]


In [76]:
print(Y_test)

[[58.31]
 [71.55]
 [65.69]
 [73.52]
 [62.65]
 [72.78]
 [56.66]
 [65.25]
 [55.5 ]
 [58.32]
 [70.48]
 [62.56]
 [55.41]
 [68.07]
 [62.72]
 [53.94]
 [54.97]
 [69.03]
 [58.87]
 [56.86]
 [69.7 ]
 [52.81]
 [62.  ]
 [64.08]
 [61.87]
 [62.74]
 [59.75]
 [71.  ]
 [77.89]
 [59.69]
 [65.48]
 [60.02]
 [62.77]
 [63.7 ]
 [51.29]
 [58.8 ]
 [60.59]
 [64.08]
 [64.15]
 [64.15]
 [62.54]
 [71.96]
 [58.95]]


## Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc =  StandardScaler()
X_train[:,0:] = sc.fit_transform(X_train[:,0:])
Y_train[:,0:] = sc.fit_transform(Y_train[:,0:])

In [78]:
print(X_train)

[[-1.30846321]
 [-0.05053648]
 [-0.05053648]
 [ 0.2290028 ]
 [ 1.90623845]
 [ 0.60218773]
 [-1.86754177]
 [-0.8891543 ]
 [-0.26019093]
 [-0.46984539]
 [ 0.92785099]
 [-0.8891543 ]
 [ 2.18577773]
 [-0.19030611]
 [ 0.08923316]
 [ 1.62669918]
 [-0.19030611]
 [ 0.36877244]
 [ 0.36877244]
 [ 0.03332531]
 [ 0.92785099]
 [-2.28685068]
 [ 0.08923316]
 [-0.29233795]
 [-0.69347681]
 [-0.91850593]
 [-0.19030611]
 [ 0.92785099]
 [ 0.78808135]
 [ 0.78808135]
 [-1.16869358]
 [ 0.68325412]
 [-0.19030611]
 [-0.19030611]
 [-0.33007575]
 [ 0.12417557]
 [-1.40630196]
 [ 0.39672637]
 [ 0.2290028 ]
 [-1.44823285]
 [-0.05053648]
 [ 3.44370447]
 [ 0.36877244]
 [ 0.36877244]
 [ 0.2290028 ]
 [-0.28395177]
 [-1.16869358]
 [-0.19030611]
 [-0.30212182]
 [-0.19030611]
 [-0.19030611]
 [ 1.76646881]
 [-0.33007575]
 [-1.44823285]
 [-0.19030611]
 [-0.8891543 ]
 [-0.19030611]
 [ 0.08923316]
 [ 1.55681436]
 [-1.16869358]
 [-1.02892394]
 [-0.74938466]
 [ 1.06762063]
 [-0.8891543 ]
 [ 0.78808135]
 [ 0.78808135]
 [-0.24621

In [79]:
print(Y_train)

[[-1.31487558e+00]
 [-3.50624077e-01]
 [-7.70316279e-01]
 [-7.18288320e-01]
 [ 7.95725282e-01]
 [-3.02064649e-01]
 [-3.31547159e-01]
 [-1.54900140e+00]
 [-4.70288383e-01]
 [-4.61617056e-01]
 [ 3.86438672e-01]
 [ 1.23969720e+00]
 [ 1.02291404e+00]
 [ 1.36704470e-01]
 [-1.98008732e-01]
 [ 1.61256423e+00]
 [-9.22931624e-01]
 [-1.23509938e+00]
 [-6.47183443e-01]
 [ 1.51197685e+00]
 [ 8.52956036e-01]
 [-1.24377070e+00]
 [ 4.73151937e-01]
 [ 7.10746282e-01]
 [ 8.23473526e-01]
 [-8.39686890e-01]
 [-1.63398039e+00]
 [ 1.67152925e+00]
 [ 1.54492789e+00]
 [-1.27151895e+00]
 [-1.44246508e-01]
 [ 1.90466694e-01]
 [ 4.90030775e-03]
 [-1.89412019e+00]
 [ 8.92844138e-01]
 [-1.82995237e+00]
 [ 4.52340754e-01]
 [ 8.33879118e-01]
 [ 5.69282666e-02]
 [-1.64612025e+00]
 [-6.36777851e-01]
 [ 1.31427060e+00]
 [ 3.95856136e-02]
 [ 5.94550508e-01]
 [-1.42512242e-01]
 [-1.51183569e-01]
 [-1.18480568e+00]
 [-8.36218360e-01]
 [ 1.73569707e+00]
 [-9.78428114e-01]
 [ 5.04368712e-01]
 [ 1.50503979e+00]
 [-1.4987077